"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {Camera,FileText,FolderOpen,Send,Upload,Users} from "lucide-react";
import QrScanner from "@/components/QrScanner";
import UserBottomNav from "@/components/UserBottomNav";

const demoReceipts=[
 {vendor:"NIS Petrol",pib:"100000111",category:"Gorivo",amount:8420,tax:1403,date:"18.09.2026",invoice:"PP-1842"},
 {vendor:"Gigatron",pib:"100000222",category:"IT oprema",amount:32990,tax:5498,date:"17.09.2026",invoice:"GT-32990"},
 {vendor:"Telekom Srbija",pib:"100000333",category:"Telekomunikacije",amount:14280,tax:2380,date:"15.09.2026",invoice:"TS-14280"}
];
const demoFiles=[
 {id:"1",name:"Ugovor_o_odrzavanju.pdf",size:"1.2 MB",source:"Fajl",status:"inbox",date:"21.09.2026"},
 {id:"2",name:"Racun_gorivo.jpg",size:"842 KB",source:"Fotografija",status:"sent",date:"20.09.2026"},
 {id:"3",name:"Izvod_septembar.pdf",size:"2.4 MB",source:"Skenirano",status:"sent",date:"19.09.2026"}
];

export default function Demo(){
 const [session,setSession]=useState<any>(null);const router=useRouter();
 const [scan,setScan]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [moreOpen,setMoreOpen]=useState(false);const [query,setQuery]=useState("");
 const [navActive,setNavActive]=useState<"home"|"search"|"files"|"more">("home");const [view,setView]=useState<"home"|"files">("home");
 const [fileTab,setFileTab]=useState<"inbox"|"sent">("inbox");const [selected,setSelected]=useState<string[]>([]);
 const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const s=JSON.parse(sessionStorage.getItem("fi_demo")||"null");if(!s)router.replace("/login?demo=1");else setSession(s)}catch{router.replace("/login?demo=1")}},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return demoReceipts;return demoReceipts.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q)))},[query]);
 if(!session)return null;
 const role=session.role;const title=role==="master"?"Master Admin":role==="accountant"?"Knjigovođa":"Demo firma";const isCompany=role==="company";
 const goHome=()=>{setView("home");setNavActive("home");setSearchOpen(false);setMoreOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 const openSearch=()=>{setNavActive("search");if(view==="files"){setTimeout(()=>searchRef.current?.focus(),80);return;}setSearchOpen(true);setMoreOpen(false);setTimeout(()=>searchRef.current?.focus(),80)};
 const openFiles=()=>{setView("files");setNavActive("files");setSearchOpen(false);setMoreOpen(false)};
 const openMore=()=>{setNavActive("more");setSearchOpen(false);setMoreOpen(true)};
 return <div className={`app-shell ${isCompany?"with-bottom-nav":""}`}><header className="appbar"><div className="container appbar-in"><a className="brand" href="/"><span className="logo">F</span><span>Fiskalni Inbox · DEMO</span></a><button className="btn" onClick={()=>{sessionStorage.removeItem("fi_demo");router.push("/")}}>Izađi iz demo-a</button></div></header><main className="container app-main">
  <div className="app-head"><div><span className="pill">{title.toUpperCase()}</span><h1>{role==="company"?"Demo Kompanija doo":title}</h1><p className="muted">Ovo su test podaci — nisu povezani sa stvarnim podacima.</p></div>{isCompany&&view==="home"&&<button className="btn btn-accent desktop-scan-btn" onClick={()=>setScan(true)}>Skeniraj QR</button>}</div>
  {role==="master"?<MasterDemo/>:role==="accountant"?<AccountantDemo/>:view==="files"?<DemoFiles query={query} setQuery={setQuery} searchRef={searchRef} tab={fileTab} setTab={setFileTab} selected={selected} setSelected={setSelected}/>:<>{searchOpen&&<div className="card user-search-card"><div className="user-search-row"><span>⌕</span><input ref={searchRef} className="user-search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pretraži demo bazu…"/>{query&&<button className="user-search-clear" onClick={()=>setQuery("")}>×</button>}</div></div>}<div className="grid stats"><Stat l="Računi" v="48"/><Stat l="Troškovi" v="318.540 RSD"/><Stat l="PDV" v="52.214 RSD"/><Stat l="Za proveru" v="2"/></div><Receipts receipts={filtered}/></>}
 </main>
 {isCompany&&scan&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setScan(false)}}><div className="modal qr-modal"><div className="modal-head"><div><span className="pill">DEMO SKENER</span><h2>QR skener</h2></div><button className="btn" onClick={()=>setScan(false)}>Zatvori</button></div><p className="muted">Kamera i očitavanje rade; demo ne upisuje podatke u produkcionu bazu.</p><QrScanner demoMode onDone={()=>setScan(false)}/></div></div>}
 {isCompany&&moreOpen&&<div className="bottom-sheet-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setMoreOpen(false)}}><div className="bottom-sheet"><div className="bottom-sheet-handle"/><div className="bottom-sheet-head"><div><span className="pill">VIŠE</span><h3>Demo opcije</h3></div><button className="btn" onClick={()=>setMoreOpen(false)}>Zatvori</button></div><div className="more-list"><div className="more-info"><span>Nalog</span><b>user / user</b></div><div className="more-info"><span>Paket</span><b>PREMIUM DEMO</b></div><button className="more-action" onClick={openFiles}>Fajlovi <b>→</b></button><button className="more-action danger" onClick={()=>{sessionStorage.removeItem("fi_demo");router.push("/")}}>Izađi iz demo-a <b>→</b></button></div></div></div>}
 {isCompany&&<UserBottomNav active={navActive} onHome={goHome} onSearch={openSearch} onScan={()=>setScan(true)} onFiles={openFiles} onMore={openMore}/>} 
 </div>
}
function Stat({l,v}:any){return <div className="card stat"><span>{l}</span><strong>{v}</strong></div>}
function Receipts({receipts}:any){return <div className="card table-card"><div className="table-tools"><b>Baza fiskalnih računa</b><button className="btn">CSV demo</button></div><div className="table-wrap"><table><thead><tr><th>Datum</th><th>Dobavljač</th><th>PIB</th><th>Kategorija</th><th>PDV</th><th>Iznos</th><th>Status</th></tr></thead><tbody>{receipts.map((r:any)=><tr key={r.vendor}><td>{r.date}</td><td><b>{r.vendor}</b><div className="muted mono" style={{fontSize:10}}>{r.invoice}</div></td><td>{r.pib}</td><td>{r.category}</td><td>{r.tax.toLocaleString("sr-RS")} RSD</td><td><b>{r.amount.toLocaleString("sr-RS")} RSD</b></td><td><span className="badge">provereno</span></td></tr>)}</tbody></table></div></div>}
function DemoFiles({query,setQuery,searchRef,tab,setTab,selected,setSelected}:any){const visible=demoFiles.filter(f=>f.status===tab&&(!query||f.name.toLowerCase().includes(query.toLowerCase())));return <><div className="grid file-action-grid"><button className="card file-action" onClick={()=>alert("Demo: otvara skeniranje dokumenta kamerom u produkcionom nalogu.")}><FileText/><div><b>Skeniraj dokument</b><span>Kamera telefona</span></div></button><button className="card file-action" onClick={()=>alert("Demo: fotografisanje dokumenta.")}><Camera/><div><b>Fotografiši</b><span>Fotografija dokumenta</span></div></button><button className="card file-action" onClick={()=>alert("Demo: izbor PDF/Word/Excel/XML/CSV fajla.")}><Upload/><div><b>Dodaj fajl</b><span>Razni tipovi fajlova</span></div></button></div><div className="card files-panel"><div className="files-toolbar"><div className="files-tabs"><button className={tab==="inbox"?"active":""} onClick={()=>setTab("inbox")}>Fajlovi</button><button className={tab==="sent"?"active":""} onClick={()=>setTab("sent")}>Poslati dokumenti</button></div><div className="files-search"><input ref={searchRef} value={query} onChange={(e:any)=>setQuery(e.target.value)} placeholder="Pretraži fajlove…"/></div></div>{tab==="inbox"&&<div className="send-bar"><span>{selected.length?`${selected.length} označeno`:"Označite dokumente"}</span><button className="btn btn-primary" disabled={!selected.length} onClick={()=>{alert("Demo: dokument je poslat knjigovođi.");setSelected([]);setTab("sent")}}><Send size={16}/> Pošalji knjigovođi</button></div>}<div className="files-list">{visible.map((f:any)=><div className="file-row" key={f.id}>{tab==="inbox"&&<label className="file-check"><input type="checkbox" checked={selected.includes(f.id)} onChange={()=>setSelected((s:string[])=>s.includes(f.id)?s.filter(x=>x!==f.id):[...s,f.id])}/><span/></label>}<div className="file-type-icon"><FileText size={20}/></div><div className="file-main"><b>{f.name}</b><span>{f.size} · {f.source} · {f.date}</span></div><div className="file-status"><span className={`badge ${f.status==="sent"?"":"warn"}`}>{f.status==="sent"?"POSLATO":"SPREMNO"}</span></div></div>)}{visible.length===0&&<div className="files-empty"><FolderOpen/><b>Nema dokumenata</b></div>}</div></div></>}
function AccountantDemo(){return <><div className="grid stats"><Stat l="Klijenti" v="6"/><Stat l="Primljeni dokumenti" v="18"/><Stat l="Računi" v="212"/><Stat l="Ovaj mesec" v="Aktivno"/></div><div className="card" style={{padding:24,marginTop:20}}><h3>Primljeni dokumenti klijenata</h3><p className="muted">U produkcionom nalogu knjigovođa vidi samo dokumente koje mu je klijent poslao.</p></div></>}
function MasterDemo(){const acc=[{name:"GK Hem",clients:6,users:14,payout:3500},{name:"Fin Konto",clients:4,users:9,payout:2250},{name:"Bilans Plus",clients:3,users:7,payout:1750}];return <><div className="grid master-stats"><Stat l="Klijenti" v="24"/><Stat l="Knjigovođe" v="8"/><Stat l="Bruto MRR" v="68.750 RSD"/><Stat l="Naknade" v="12.500 RSD"/><Stat l="Profit*" v="56.250 RSD"/></div><div className="master-note">Obračun knjigovođa: 250 RSD po korisniku aplikacije. Datum obračuna: poslednji dan u mesecu.</div><div className="grid accountant-grid" style={{marginTop:20}}>{acc.map(a=><div className="card accountant-card" key={a.name}><div className="accountant-head"><div className="accountant-avatar"><Users/></div><div><h3>{a.name}</h3><span>Demo knjigovođa</span></div></div><div className="accountant-kpis"><div><span>Klijenti</span><b>{a.clients}</b></div><div><span>Korisnici</span><b>{a.users}</b></div><div><span>Za uplatu</span><b>{a.payout.toLocaleString("sr-RS")} RSD</b></div></div></div>)}</div></>}
