"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import BrandWordmark from "@/components/BrandWordmark";
import {Camera,FileText,FolderOpen,ImagePlus,Send,Sparkles,Upload,Users} from "lucide-react";
import QrScanner from "@/components/QrScanner";
import UserBottomNav from "@/components/UserBottomNav";
import {RECEIPT_CATEGORIES} from "@/lib/receipt-category";

const initialDemoReceipts=[
 {id:"r1",vendor:"NIS Petrol",pib:"100000111",category:"Gorivo",amount:8420,tax:1403,date:"18.09.2026",invoice:"PP-1842",sent:false,auto:true},
 {id:"r2",vendor:"Gigatron",pib:"100000222",category:"IT oprema",amount:32990,tax:5498,date:"17.09.2026",invoice:"GT-32990",sent:true,auto:true},
 {id:"r3",vendor:"Telekom Srbija",pib:"100000333",category:"Telekomunikacije",amount:14280,tax:2380,date:"15.09.2026",invoice:"TS-14280",sent:true,auto:true},
 {id:"r4",vendor:"Putevi Srbije",pib:"100000444",category:"Putarina",amount:1260,tax:210,date:"14.09.2026",invoice:"ENP-1260",sent:false,auto:true}
];
const demoFiles=[
 {id:"1",name:"Ugovor_o_odrzavanju.pdf",size:"1.2 MB",source:"Fajl",status:"inbox",date:"21.09.2026"},
 {id:"2",name:"Racun_gorivo.jpg",size:"842 KB",source:"Fotografija",status:"sent",date:"20.09.2026"},
 {id:"3",name:"Izvod_septembar.pdf",size:"2.4 MB",source:"Skenirano",status:"sent",date:"19.09.2026"}
];
const money=(n:number)=>new Intl.NumberFormat("sr-RS",{style:"currency",currency:"RSD"}).format(n);

export default function Demo(){
 const [session,setSession]=useState<any>(null);const router=useRouter();
 const [receipts,setReceipts]=useState<any[]>(initialDemoReceipts);
 const [scan,setScan]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [moreOpen,setMoreOpen]=useState(false);const [query,setQuery]=useState("");
 const [category,setCategory]=useState("Sve");const [sendSchedule,setSendSchedule]=useState("manual");const [message,setMessage]=useState("");
 const [logo,setLogo]=useState<string>("");const logoRef=useRef<HTMLInputElement>(null);
 const [navActive,setNavActive]=useState<"home"|"search"|"files"|"more">("home");const [view,setView]=useState<"home"|"files">("home");
 const [fileTab,setFileTab]=useState<"inbox"|"sent">("inbox");const [selected,setSelected]=useState<string[]>([]);
 const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const s=JSON.parse(sessionStorage.getItem("fi_demo")||"null");if(!s)router.replace("/login?demo=1");else setSession(s)}catch{router.replace("/login?demo=1")}},[router]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return receipts.filter(r=>(category==="Sve"||r.category===category)&&(!q||Object.values(r).some(v=>String(v).toLowerCase().includes(q))))},[query,category,receipts]);
 const categoryTotals=useMemo(()=>{const m=new Map<string,number>();receipts.forEach(r=>m.set(r.category,(m.get(r.category)||0)+r.amount));return Array.from(m.entries()).sort((a,b)=>b[1]-a[1])},[receipts]);
 if(!session)return null;
 const role=session.role;const title=role==="master"?"Master Admin":role==="accountant"?"Knjigovođa":"Demo firma";const isCompany=role==="company";
 const goHome=()=>{setView("home");setNavActive("home");setSearchOpen(false);setMoreOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 const openSearch=()=>{setNavActive("search");if(view==="files"){setTimeout(()=>searchRef.current?.focus(),80);return;}setSearchOpen(true);setMoreOpen(false);setTimeout(()=>searchRef.current?.focus(),80)};
 const openFiles=()=>{setView("files");setNavActive("files");setSearchOpen(false);setMoreOpen(false)};
 const openMore=()=>{setNavActive("more");setSearchOpen(false);setMoreOpen(true)};
 const sendNow=()=>{const n=receipts.filter(r=>!r.sent).length;setReceipts(old=>old.map(r=>({...r,sent:true})));setMessage(n?`${n} demo račun(a) poslato knjigovođi.`:"Nema novih računa za slanje.")};
 const scanDone=(result:any)=>{const id=`r${Date.now()}`;setReceipts(old=>[{id,vendor:"Demo fiskalni račun",pib:"109999999",category:"Ostalo",amount:2450,tax:408.33,date:new Date().toLocaleDateString("sr-RS"),invoice:"DEMO-QR",sent:false,auto:true},...old]);setScan(false);setMessage("QR je očitan i račun je odmah dodat u Ostalo.")};
 const uploadLogo=(file?:File)=>{if(!file)return;const u=URL.createObjectURL(file);setLogo(old=>{if(old)URL.revokeObjectURL(old);return u});setMessage("Demo logo je dodat.")};
 return <div className={`app-shell ${isCompany?"with-bottom-nav":""}`}><header className="appbar"><div className="container appbar-in"><a className="brand" href="/"><span className="logo">F</span><BrandWordmark suffix=" · DEMO"/></a><button className="btn demo-logout-button" onClick={()=>{sessionStorage.removeItem("fi_demo");router.push("/")}}>Izađi iz demo-a</button></div></header><main className="container app-main">
  <div className="app-head company-home-head"><div className="company-identity">{isCompany&&<div className="company-logo-wrap">{logo?<img className="company-logo-image" src={logo} alt="Demo logo"/>:<div className="company-logo-placeholder">D</div>}<button className="company-logo-edit" onClick={()=>logoRef.current?.click()}><ImagePlus size={16}/></button><input hidden ref={logoRef} type="file" accept="image/*" onChange={e=>uploadLogo(e.target.files?.[0])}/></div>}<div><span className="pill">{title.toUpperCase()}</span><h1>{role==="company"?"Demo Kompanija doo":title}</h1><p className="muted">Ovo su test podaci — nisu povezani sa stvarnim podacima.</p></div></div>{isCompany&&view==="home"&&<div className="actions"><button className="btn btn-primary" onClick={sendNow}><Send size={17}/> Pošalji knjigovođi ({receipts.filter(r=>!r.sent).length})</button><button className="btn btn-accent desktop-scan-btn" onClick={()=>setScan(true)}>Skeniraj QR</button></div>}</div>
  {message&&<div className="home-message">{message}</div>}
  {role==="master"?<MasterDemo/>:role==="accountant"?<AccountantDemo/>:view==="files"?<DemoFiles query={query} setQuery={setQuery} searchRef={searchRef} tab={fileTab} setTab={setFileTab} selected={selected} setSelected={setSelected}/>:<>{searchOpen&&<div className="card user-search-card"><div className="user-search-row"><span>⌕</span><input ref={searchRef} className="user-search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pretraži demo bazu…"/>{query&&<button className="user-search-clear" onClick={()=>setQuery("")}>×</button>}</div></div>}<div className="grid stats"><Stat l="Računi" v={receipts.length}/><Stat l="Troškovi" v={money(receipts.reduce((s,r)=>s+r.amount,0))}/><Stat l="PDV" v={money(receipts.reduce((s,r)=>s+r.tax,0))}/><Stat l="Čeka slanje" v={receipts.filter(r=>!r.sent).length}/></div><div className="card expense-overview"><div className="expense-overview-head"><div><span className="pill"><Sparkles size={13}/> AUTO KATEGORIJE</span><h3>Pregled po vrsti troška</h3></div><select className="select" value={category} onChange={e=>setCategory(e.target.value)}><option value="Sve">Sve kategorije</option>{RECEIPT_CATEGORIES.map((c:string)=><option key={c}>{c}</option>)}</select></div><div className="expense-category-grid">{categoryTotals.map(([c,t]:[string,number])=><button className={`expense-category ${category===c?"active":""}`} key={c} onClick={()=>setCategory(category===c?"Sve":c)}><span>{c}</span><b>{money(t)}</b></button>)}</div></div><Receipts receipts={filtered}/></>}
 </main>
 {isCompany&&scan&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setScan(false)}}><div className="modal qr-modal"><div className="modal-head"><div><span className="pill">DEMO SKENER</span><h2>QR skener</h2></div><button className="btn" onClick={()=>setScan(false)}>Zatvori</button></div><p className="muted">Posle očitavanja demo račun se odmah dodaje na listu.</p><QrScanner demoMode onDone={scanDone}/></div></div>}
 {isCompany&&moreOpen&&<div className="bottom-sheet-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setMoreOpen(false)}}><div className="bottom-sheet"><div className="bottom-sheet-handle"/><div className="bottom-sheet-head"><div><span className="pill">VIŠE</span><h3>Demo opcije</h3></div><button className="btn" onClick={()=>setMoreOpen(false)}>Zatvori</button></div><div className="more-list"><div className="more-info"><span>Nalog</span><b>user / user</b></div><div className="more-info"><span>Paket</span><b>PREMIUM DEMO</b></div><div className="auto-send-settings"><b>Automatsko slanje</b><select className="select" value={sendSchedule} onChange={e=>setSendSchedule(e.target.value)}><option value="manual">Isključeno</option><option value="weekly">Nedeljno — petkom</option><option value="monthly">Mesečno — poslednjeg dana</option></select><button className="btn btn-primary" onClick={()=>setMessage("Demo raspored je sačuvan.")}>Sačuvaj raspored</button></div><button className="more-action" onClick={sendNow}>Pošalji račune sada <b>→</b></button><button className="more-action" onClick={openFiles}>Fajlovi <b>→</b></button><button className="more-action danger" onClick={()=>{sessionStorage.removeItem("fi_demo");router.push("/")}}>Izađi iz demo-a <b>→</b></button></div></div></div>}
 {isCompany&&<UserBottomNav active={navActive} onHome={goHome} onSearch={openSearch} onScan={()=>setScan(true)} onFiles={openFiles} onMore={openMore}/>} 
 </div>
}
function Stat({l,v}:any){return <div className="card stat"><span>{l}</span><strong>{v}</strong></div>}
function Receipts({receipts}:any){return <div className="card table-card"><div className="table-tools"><b>Baza fiskalnih računa</b><button className="btn">CSV demo</button></div><div className="table-wrap"><table><thead><tr><th>Datum</th><th>Dobavljač</th><th>PIB</th><th>Kategorija</th><th>PDV</th><th>Iznos</th><th>Knjigovođa</th></tr></thead><tbody>{receipts.map((r:any)=><tr key={r.id}><td>{r.date}</td><td><b>{r.vendor}</b><div className="muted mono" style={{fontSize:10}}>{r.invoice}</div></td><td>{r.pib}</td><td>{r.category}{r.auto&&<small className="auto-category"><Sparkles size={10}/> AUTO</small>}</td><td>{money(r.tax)}</td><td><b>{money(r.amount)}</b></td><td><span className={`badge ${r.sent?"":"warn"}`}>{r.sent?"POSLATO":"ČEKA"}</span></td></tr>)}</tbody></table></div></div>}
function DemoFiles({query,setQuery,searchRef,tab,setTab,selected,setSelected}:any){const visible=demoFiles.filter(f=>f.status===tab&&(!query||f.name.toLowerCase().includes(query.toLowerCase())));return <><div className="grid file-action-grid"><button className="card file-action" onClick={()=>alert("Demo: otvara skeniranje dokumenta kamerom u produkcionom nalogu.")}><FileText/><div><b>Skeniraj dokument</b><span>Kamera telefona</span></div></button><button className="card file-action" onClick={()=>alert("Demo: fotografisanje dokumenta.")}><Camera/><div><b>Fotografiši</b><span>Fotografija dokumenta</span></div></button><button className="card file-action" onClick={()=>alert("Demo: izbor PDF/Word/Excel/XML/CSV fajla.")}><Upload/><div><b>Dodaj fajl</b><span>Razni tipovi fajlova</span></div></button></div><div className="card files-panel"><div className="files-toolbar"><div className="files-tabs"><button className={tab==="inbox"?"active":""} onClick={()=>setTab("inbox")}>Fajlovi</button><button className={tab==="sent"?"active":""} onClick={()=>setTab("sent")}>Poslati dokumenti</button></div><div className="files-search"><input ref={searchRef} value={query} onChange={(e:any)=>setQuery(e.target.value)} placeholder="Pretraži fajlove…"/></div></div>{tab==="inbox"&&<div className="send-bar"><span>{selected.length?`${selected.length} označeno`:"Označite dokumente"}</span><button className="btn btn-primary" disabled={!selected.length} onClick={()=>{alert("Demo: dokument je poslat knjigovođi.");setSelected([]);setTab("sent")}}><Send size={16}/> Pošalji knjigovođi</button></div>}<div className="files-list">{visible.map((f:any)=><div className="file-row" key={f.id}>{tab==="inbox"&&<label className="file-check"><input type="checkbox" checked={selected.includes(f.id)} onChange={()=>setSelected((s:string[])=>s.includes(f.id)?s.filter(x=>x!==f.id):[...s,f.id])}/><span/></label>}<div className="file-type-icon"><FileText size={20}/></div><div className="file-main"><b>{f.name}</b><span>{f.size} · {f.source} · {f.date}</span></div><div className="file-status"><span className={`badge ${f.status==="sent"?"":"warn"}`}>{f.status==="sent"?"POSLATO":"SPREMNO"}</span></div></div>)}{visible.length===0&&<div className="files-empty"><FolderOpen/><b>Nema dokumenata</b></div>}</div></div></>}
function AccountantDemo(){const clients=[{name:"Demo Kompanija doo",newR:4,newD:2,vat:8410},{name:"Nova Office doo",newR:1,newD:0,vat:5220},{name:"Servis Plus",newR:0,newD:3,vat:3140}];return <><div className="grid accountant-summary-grid"><div className="card accountant-summary-card"><div className="accountant-summary-icon"><FileText/></div><div><span>Novi dokumenti</span><strong>5</strong><small>neotvoreni</small></div></div><div className="card accountant-summary-card"><div className="accountant-summary-icon"><Sparkles/></div><div><span>Novi računi</span><strong>7</strong><small>neotvoreni</small></div></div><div className="card accountant-summary-card"><div className="accountant-summary-icon"><FileText/></div><div><span>Preuzeti računi</span><strong>34</strong><small>ovog meseca</small></div></div><div className="card accountant-summary-card"><div className="accountant-summary-icon"><FolderOpen/></div><div><span>Preuzeti dokumenti</span><strong>12</strong><small>ovog meseca</small></div></div></div><div className="grid deadline-grid"><div className="card deadline-card"><FileText/><div><span>Obračun / fakture</span><b>do 10. u mesecu</b><small>za prethodni mesec</small></div></div><div className="card deadline-card"><Sparkles/><div><span>PDV prijava</span><b>15. u mesecu</b><small>rok za prijavu</small></div></div></div><section className="accountant-section"><div className="section-title"><div><span className="pill">KLIJENTI</span><h2>Klijenti</h2></div></div><div className="grid accountant-client-grid">{clients.map(c=><button className="card accountant-client-card" key={c.name} onClick={()=>alert(`Demo pregled klijenta: ${c.name} — računi, dokumenti, preuzimanje, štampa i PDV arhiva.`)}><div className="accountant-client-top"><div><h3>{c.name}</h3><span>Demo klijent</span></div>{c.newR+c.newD>0&&<span className="new-counter">{c.newR+c.newD} novo</span>}</div><div className="accountant-client-kpis"><div><span>Novi računi</span><b>{c.newR}</b></div><div><span>Novi dokumenti</span><b>{c.newD}</b></div><div><span>Ulazni PDV</span><b>{money(c.vat)}</b></div></div><div className="client-open">Otvori klijenta →</div></button>)}</div></section></>}
function MasterDemo(){const acc=[{name:"GK Hem",clients:6,users:14,payout:3500},{name:"Fin Konto",clients:4,users:9,payout:2250},{name:"Bilans Plus",clients:3,users:7,payout:1750}];return <><div className="grid master-stats"><Stat l="Klijenti" v="24"/><Stat l="Knjigovođe" v="8"/><Stat l="Bruto MRR" v="68.750 RSD"/><Stat l="Naknade" v="12.500 RSD"/><Stat l="Profit*" v="56.250 RSD"/></div><div className="master-note">Obračun knjigovođa: 250 RSD po korisniku aplikacije. Datum obračuna: poslednji dan u mesecu.</div><div className="grid accountant-grid" style={{marginTop:20}}>{acc.map(a=><div className="card accountant-card" key={a.name}><div className="accountant-head"><div className="accountant-avatar"><Users/></div><div><h3>{a.name}</h3><span>Demo knjigovođa</span></div></div><div className="accountant-kpis"><div><span>Klijenti</span><b>{a.clients}</b></div><div><span>Korisnici</span><b>{a.users}</b></div><div><span>Za uplatu</span><b>{a.payout.toLocaleString("sr-RS")} RSD</b></div></div></div>)}</div></>}
