'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import CompanySearch,{type CompanySearchValue} from '@/components/CompanySearch';
export default function SetupForm(){
  const router=useRouter();const [company,setCompany]=useState<CompanySearchValue|null>(null);const [plan,setPlan]=useState<'basic'|'premium'>('basic');const [trial,setTrial]=useState(true);const [saving,setSaving]=useState(false);const [err,setErr]=useState('');
  async function save(e:React.FormEvent){e.preventDefault();if(!company){setErr('Izaberite firmu iz APR pretrage.');return;}setErr('');setSaving(true);try{const r=await fetch('/api/org/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company_id:company.id,plan,trial})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Kreiranje firme nije uspelo.');if(d.access_request_pending){router.push('/app');router.refresh();return;}if(d.checkout_required){const cr=await fetch('/api/subscriptions/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organization_id:d.id,plan})});const cd=await cr.json();if(!cr.ok)throw new Error(cd.error||'Online pretplata nije mogla da se pokrene.');window.location.href=cd.url;return;}router.push('/app?org='+d.id);router.refresh();}catch(e:any){setErr(e.message||'Greška pri povezivanju firme.');}finally{setSaving(false);}}
  return <form onSubmit={save} className="setup-company-form"><CompanySearch value={company} onSelect={setCompany} label="Pronađite svoju firmu" required placeholder="Naziv firme ili matični broj" showDetails/><div className="setup-grid" style={{marginTop:18}}><div className="field"><label>Paket</label><select className="select" value={plan} onChange={e=>setPlan(e.target.value as any)}><option value="basic">Basic — 1.250 RSD + PDV / korisnik</option><option value="premium">Premium — 1.790 RSD + PDV / korisnik</option></select></div><div className="field"><label>Početak</label><select className="select" value={trial?'trial':'paid'} onChange={e=>setTrial(e.target.value==='trial')}><option value="trial">Probaj 10 dana besplatno</option><option value="paid">Aktiviraj pretplatu odmah</option></select></div></div>{err&&<div className="error">{err}</div>}<button className="btn btn-primary" style={{width:'100%',marginTop:16}} disabled={saving||!company}>{saving?'Povezujem firmu…':trial?'Ovo je moja firma — pokreni trial':'Ovo je moja firma — pređi na plaćanje'}</button></form>;
}
