"use client";
import { useEffect, useRef, useState } from "react";
import { Building2, ChevronDown, LogOut, UserRound } from "lucide-react";
import CommunicationQuickActions from "@/components/CommunicationQuickActions";

export default function CompanyHeaderMenu({profile,organization,logoAvailable,logoVersion=0}:{profile:any;organization:any;logoAvailable?:boolean;logoVersion?:number}){
  const [open,setOpen]=useState(false);const ref=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{if(!open)return;const outside=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};document.addEventListener('mousedown',outside);document.addEventListener('keydown',esc);return()=>{document.removeEventListener('mousedown',outside);document.removeEventListener('keydown',esc)}},[open]);
  if(!organization)return <div className="legacy-header-account"><span className="muted">{profile?.username}</span><form method="post" action="/api/auth/logout"><button className="btn">Odjava</button></form></div>;
  const orgId=organization.organization_id||organization.id||'';const orgName=organization.name||profile?.username||'Nalog';const hasLogo=logoAvailable??Boolean(organization.logo_path);
  const avatar=<span className="company-header-avatar">{hasLogo?<img src={`/api/org/logo?organization_id=${orgId}&v=${logoVersion}`} alt={`Logo ${orgName}`}/>:<span>{String(orgName).slice(0,1).toUpperCase()}</span>}</span>;
  return <div className="company-header-cluster"><CommunicationQuickActions/><div className="company-header-menu" ref={ref}><button type="button" className={`company-header-trigger ${open?'open':''}`} onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-haspopup="menu">{avatar}<span className="company-header-copy"><small>Aktivna firma</small><b>{orgName}</b><span className="company-header-meta">{organization.pib?`PIB ${organization.pib}`:'FiscalBox nalog'}</span></span><ChevronDown size={16} className="company-header-chevron"/></button>{open&&<div className="company-header-dropdown" role="menu"><div className="company-header-dropdown-title"><span className="company-header-avatar small">{hasLogo?<img src={`/api/org/logo?organization_id=${orgId}&v=${logoVersion}`} alt=""/>:<span>{String(orgName).slice(0,1).toUpperCase()}</span>}</span><div><b>{orgName}</b><span>{organization.pib?`PIB ${organization.pib}`:'FiscalBox nalog'}</span></div></div><a role="menuitem" href={`/app/settings?section=company&org=${orgId}`}><Building2 size={17}/><span><b>Podešavanja kompanije</b><small>Podaci firme i kontakt</small></span></a><a role="menuitem" href={`/app/settings?section=user&org=${orgId}`}><UserRound size={17}/><span><b>Podešavanja korisnika</b><small>Profil i lozinka</small></span></a><form method="post" action="/api/auth/logout"><button role="menuitem" type="submit" className="company-header-logout"><LogOut size={17}/><span><b>Izloguj se</b><small>Završi trenutnu sesiju</small></span></button></form></div>}</div></div>
}
