'use client';
import React from 'react';
import { FilePlus2, Megaphone, Paperclip, Send, Trash2 } from 'lucide-react';

type Att={name:string;path:string;mime_type:string;size_bytes:number};
export default function MasterMarketingPanel({selected,onMessage,campaigns=[]}:{selected:string[];onMessage:(m:string)=>void;campaigns?:any[]}){
  const [name,setName]=React.useState('');const [subject,setSubject]=React.useState('');const [message,setMessage]=React.useState('');const [attachments,setAttachments]=React.useState<Att[]>([]);const [busy,setBusy]=React.useState('');
  async function upload(files:FileList|null){if(!files?.length)return;setBusy('upload');try{for(const file of Array.from(files).slice(0,5-attachments.length)){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/master/marketing/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||`Upload nije uspeo: ${file.name}`);setAttachments(v=>[...v,d.file]);}onMessage('Marketing prilozi su uploadovani.');}catch(e:any){onMessage(e.message||'Upload nije uspeo.');}finally{setBusy('')}}
  async function send(){setBusy('send');try{const r=await fetch('/api/master/marketing/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organization_ids:selected,name,subject,message,attachments})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Marketing poruka nije poslata.');onMessage(d.message||`Poslato ${d.sent_count}/${d.recipient_count}.`);setName('');setSubject('');setMessage('');setAttachments([]);setTimeout(()=>location.reload(),900);}catch(e:any){onMessage(e.message||'Marketing poruka nije poslata.');}finally{setBusy('')}}
  const total=attachments.reduce((s,a)=>s+Number(a.size_bytes||0),0);
  return <><section className="card master46-panel master-marketing-panel"><div className="section-title"><div><span className="pill"><Megaphone size={13}/> MARKETING</span><h2>Reklamne poruke i fajlovi</h2></div><span className="muted">Primaoci se koriste iz izbora iznad · {selected.length} izabrano</span></div><div className="grid master46-form-grid"><div><div className="field"><label>Naziv kampanje</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="npr. Oktobarska akcija"/></div><div className="field"><label>Naslov emaila</label><input className="input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Naslov koji vidi primalac"/></div><div className="field"><label>Reklamna poruka</label><textarea className="textarea" rows={8} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Unesite marketing poruku…"/></div></div><div><div className="master-marketing-drop"><FilePlus2 size={28}/><b>Dodaj priloge</b><span>PDF, slike, TXT/CSV, DOCX ili XLSX · do 10 MB po fajlu · do 5 fajlova</span><label className="btn"><Paperclip size={15}/> {busy==='upload'?'Upload…':'Izaberi fajlove'}<input type="file" multiple hidden disabled={!!busy||attachments.length>=5} onChange={e=>upload(e.target.files)}/></label></div><div className="master-marketing-files">{attachments.map((a,i)=><div key={a.path}><div><b>{a.name}</b><span>{(a.size_bytes/1024/1024).toFixed(2)} MB</span></div><button type="button" onClick={()=>setAttachments(v=>v.filter((_,x)=>x!==i))}><Trash2 size={14}/></button></div>)}{!attachments.length&&<span className="muted">Nema dodatih priloga.</span>}</div><small className="muted">Ukupno priloga: {(total/1024/1024).toFixed(2)} MB / 20 MB</small></div></div><button className="btn btn-primary" disabled={!selected.length||!subject||!message||!!busy||total>20*1024*1024} onClick={send}><Send size={15}/> {busy==='send'?'Šaljem kampanju…':'Pošalji marketing kampanju'}</button></section>
  {campaigns.length>0&&<section className="card master46-panel" style={{marginTop:16}}><span className="pill">ISTORIJA MARKETINGA</span><h2>Poslednje kampanje</h2><div className="master46-doc-list">{campaigns.slice(0,12).map((c:any)=><div key={c.id}><div><b>{c.name||c.subject}</b><span>{new Intl.DateTimeFormat('sr-RS',{dateStyle:'medium',timeStyle:'short'}).format(new Date(c.sent_at||c.created_at))} · {c.status}</span></div><div><b>{c.sent_count}/{c.recipient_count}</b><span>poslato</span></div></div>)}</div></section>}</>;
}
