import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { createInviteToken, hashInviteToken } from '@/lib/invite-token';
import { sendClientInvite } from '@/lib/mailer';
import { sendSms } from '@/lib/sms';
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export async function POST(request:Request){
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Niste prijavljeni.'},{status:401});const body=await request.json();const companyId=String(body.company_id||'');const email=String(body.email||'').trim().toLowerCase();const phone=String(body.phone||'').trim();const channel=['email','sms','both'].includes(body.channel)?body.channel:'email';if(!companyId)return NextResponse.json({error:'Izaberite klijenta iz APR pretrage.'},{status:400});if(!EMAIL.test(email))return NextResponse.json({error:'Unesite ispravan email klijenta.'},{status:400});if(channel!=='email'&&!phone)return NextResponse.json({error:'Unesite broj telefona klijenta.'},{status:400});
  const {data:officeMemberships}=await supabase.from('organization_members').select('organization_id,role,accounting_access_role,organizations(id,name,owner_user_id,organization_type)').eq('user_id',user.id).in('role',['owner','employee']);const officeMembership:any=(officeMemberships||[]).find((m:any)=>m.organizations?.organization_type==='accounting');if(!officeMembership)return NextResponse.json({error:'Nalog nije povezan sa knjigovodstvenom agencijom.'},{status:403});if(officeMembership.role!=='owner'&&officeMembership.accounting_access_role!=='admin')return NextResponse.json({error:'Samo administrator agencije može povezivati klijente.'},{status:403});const office:any=officeMembership.organizations;const admin=createAdminClient();const {data:company}=await admin.from('companies').select('*').eq('id',companyId).maybeSingle();if(!company)return NextResponse.json({error:'Firma nije pronađena u centralnoj bazi.'},{status:404});
  const {data:existingOrg}=await admin.from('organizations').select('id,name,owner_user_id').eq('company_id',companyId).eq('organization_type','company').limit(1).maybeSingle();if(existingOrg){await admin.from('accountant_company').upsert({accountant_organization_id:office.id,company_id:companyId,client_organization_id:existingOrg.id,status:'pending',requested_by:user.id,updated_at:new Date().toISOString()},{onConflict:'accountant_organization_id,company_id'});return NextResponse.json({ok:true,linked_existing:false,request_sent:true,organization_id:existingOrg.id,name:existingOrg.name,message:'Firma već ima FiscalBox nalog. Poslat je zahtev administratoru firme za povezivanje.'});}
  const token=createInviteToken();const tokenHash=await hashInviteToken(token);const snapshot={name:company.name,pib:company.pib,registration_number:company.registration_number,legal_form:company.legal_form,address:company.address,city:company.city,municipality:company.municipality,postal_code:company.postal_code,activity_code:company.activity_code,activity_name:company.activity_name,registry_status:company.registry_status,apr_source_id:company.apr_source_id,apr_last_sync:company.apr_last_sync};const expiresAt=new Date(Date.now()+30*24*60*60*1000).toISOString();const {data:invite,error}=await admin.from('client_invitations').insert({accounting_organization_id:office.id,invited_by:user.id,assigned_employee_id:officeMembership.role==='employee'?user.id:null,company_id:companyId,company_pib:company.pib||'',company_registration_number:company.registration_number,company_name:company.name,company_snapshot:snapshot,email,phone,invite_channel:channel,token_hash:tokenHash,expires_at:expiresAt}).select('id').single();if(error||!invite)return NextResponse.json({error:error?.message||'Poziv nije sačuvan.'},{status:400});
  await admin.from('accountant_company').upsert({accountant_organization_id:office.id,company_id:companyId,status:'pending',requested_by:user.id,updated_at:new Date().toISOString()},{onConflict:'accountant_organization_id,company_id'});
  const origin=new URL(request.url).origin;const inviteUrl=`${origin}/invite/client?token=${encodeURIComponent(token)}`;let emailResult:any={sent:false,configured:false};let smsResult:any={sent:false,configured:false};if(channel==='email'||channel==='both'){try{emailResult=await sendClientInvite({to:email,accountingOffice:office.name,companyName:company.name,inviteUrl});}catch{}}if(channel==='sms'||channel==='both'){try{smsResult=await sendSms({to:phone,body:`${office.name} vas poziva u FiscalBox za ${company.name}. Aktivacija: ${inviteUrl}`});}catch{}}await admin.from('client_invitations').update({sent_at:(emailResult.sent||smsResult.sent)?new Date().toISOString():null}).eq('id',invite.id);return NextResponse.json({ok:true,invite_id:invite.id,company,email:emailResult,sms:smsResult});
}
