"use client";
import React from 'react';
import { Bell, Download, ImagePlus, Save, Settings, UserPlus, Users } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { createClient as createBrowserSupabase } from '@/lib/supabase/client';
import InstallAppButton from '@/components/InstallAppButton';

export default function AccountantSettings({profile,office,isAdmin,initialSettings,staff,clients,assignments}:any){
  const router=useRouter();
  const [tab,setTab]=React.useState<'profile'|'notifications'|'staff'|'install'>('profile');
  const [settings,setSettings]=React.useState(initialSettings);
  const [message,setMessage]=React.useState('');
  const [busy,setBusy]=React.useState(false);
  const [logoVersion,setLogoVersion]=React.useState(Date.now());
  const [logoAvailable,setLogoAvailable]=React.useState(Boolean(office.logo_path));
  const fileRef=React.useRef<HTMLInputElement>(null);
  const [newStaff,setNewStaff]=React.useState({full_name:'',username:'',email:'',password:''});
  const [staffMessage,setStaffMessage]=React.useState('');
  const [assignmentState,setAssignmentState]=React.useState<Record<string,string[]>>(()=>{
    const map:Record<string,string[]>={};
    for(const s of staff||[])map[String(s.user_id)]=(assignments||[]).filter((a:any)=>String(a.employee_user_id)===String(s.user_id)).map((a:any)=>String(a.client_organization_id));
    return map;
  });

  async function cropLogo(file:File){
    const url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();
    const size=640;const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);
    const ratio=img.width/img.height;
    if(ratio>1.8||ratio<0.55){const scale=Math.min((size*.88)/img.width,(size*.88)/img.height);const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h)}
    else {const side=Math.min(img.width,img.height);const sx=(img.width-side)/2,sy=(img.height-side)/2;ctx.drawImage(img,sx,sy,side,side,0,0,size,size)}
    URL.revokeObjectURL(url);const blob:Blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Slika nije obrađena.')),'image/jpeg',.9));return new File([blob],'logo.jpg',{type:'image/jpeg'});
  }
  async function uploadLogo(file?:File){
    if(!file)return;setMessage('Obrađujem i čuvam logo…');setBusy(true);
    try{const cropped=await cropLogo(file);const tr=await fetch('/api/org/logo/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organization_id:office.organization_id,file_name:cropped.name,size_bytes:cropped.size})});const td=await tr.json();if(!tr.ok)throw new Error(td.error||'Upload nije pripremljen.');const browser=createBrowserSupabase();const up=await browser.storage.from('organization-assets').uploadToSignedUrl(td.path,td.token,cropped,{contentType:'image/jpeg'});if(up.error)throw up.error;const rr=await fetch('/api/org/logo/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organization_id:office.organization_id,path:td.path})});const rd=await rr.json();if(!rr.ok)throw new Error(rd.error||'Logo nije sačuvan.');setLogoAvailable(true);setLogoVersion(Date.now());setMessage('Logo agencije je sačuvan.');router.refresh()}catch(e:any){setMessage(e.message||'Logo nije sačuvan.')}finally{setBusy(false);if(fileRef.current)fileRef.current.value=''}}
  async function saveSettings(){setBusy(true);setMessage('');const r=await fetch('/api/accountant/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accounting_organization_id:office.organization_id,...settings})});const d=await r.json();setBusy(false);setMessage(r.ok?'Podešavanja notifikacija su sačuvana.':d.error||'Greška.');}
  async function createStaff(e:React.FormEvent){e.preventDefault();setBusy(true);setStaffMessage('');const r=await fetch('/api/accountant/staff/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accounting_organization_id:office.organization_id,...newStaff})});const d=await r.json();setBusy(false);if(!r.ok){setStaffMessage(d.error||'Nalog nije kreiran.');return}setStaffMessage(`Nalog ${d.username} je kreiran.`);setNewStaff({full_name:'',username:'',email:'',password:''});router.refresh()}
  function toggleClient(employeeId:string,clientId:string){setAssignmentState(old=>{const current=old[employeeId]||[];return {...old,[employeeId]:current.includes(clientId)?current.filter(x=>x!==clientId):[...current,clientId]}})}
  async function saveAssignments(employeeId:string){setBusy(true);setStaffMessage('');const r=await fetch('/api/accountant/staff/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accounting_organization_id:office.organization_id,employee_user_id:employeeId,client_ids:assignmentState[employeeId]||[]})});const d=await r.json();setBusy(false);setStaffMessage(r.ok?'Dodela klijenata je sačuvana.':d.error||'Greška pri dodeli.');router.refresh()}

  return <div className="app-shell accountant-shell"><header className="appbar"><div className="container appbar-in"><a className="brand" href="/app"><span className="logo">F</span><span>FiscalBox · KNJIGO</span></a><a className="btn" href="/app">← Dashboard</a></div></header><main className="container app-main"><div className="app-head"><div><span className="pill"><Settings size={13}/> PODEŠAVANJA</span><h1>{office.name}</h1><p className="muted">Profil agencije, notifikacije, zaposleni i desktop aplikacija.</p></div></div>
  <div className="settings-tabs"><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profil / logo</button><button className={tab==='notifications'?'active':''} onClick={()=>setTab('notifications')}>Notifikacije</button>{isAdmin&&<button className={tab==='staff'?'active':''} onClick={()=>setTab('staff')}>Zaposleni</button>}<button className={tab==='install'?'active':''} onClick={()=>setTab('install')}>Desktop app</button></div>
  {tab==='profile'&&<div className="card settings-card"><div className="settings-logo-row"><div className="accounting-logo-large">{logoAvailable?<img src={`/api/org/logo?organization_id=${office.organization_id}&v=${logoVersion}`} alt="Logo agencije"/>:<span>{String(office.name||'K').slice(0,1)}</span>}</div><div><h2>Logo knjigovodstvene agencije</h2><p className="muted">Ubacite JPG/PNG. Sistem automatski pravi kvadratni profilni format; za široke logoe čuva ceo znak sa belom pozadinom.</p><button className="btn btn-primary" onClick={()=>fileRef.current?.click()} disabled={busy}><ImagePlus size={17}/> Dodaj / promeni logo</button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadLogo(e.target.files?.[0])}/></div></div>{message&&<div className="demo-box">{message}</div>}</div>}
  {tab==='notifications'&&<div className="card settings-card"><h2>Notifikacije</h2><p className="muted">Izaberite šta želite da vidite u centru obaveštenja na KNJIGO dashboard-u.</p><label className="toggle-row"><span><b>Novi računi</b><small>Obaveštenje za nove neotvorene fiskalne račune.</small></span><input type="checkbox" checked={settings.notify_new_receipts!==false} onChange={e=>setSettings({...settings,notify_new_receipts:e.target.checked})}/></label><label className="toggle-row"><span><b>Novi dokumenti</b><small>Obaveštenje kada klijent pošalje novi fajl.</small></span><input type="checkbox" checked={settings.notify_new_documents!==false} onChange={e=>setSettings({...settings,notify_new_documents:e.target.checked})}/></label><label className="toggle-row"><span><b>Rokovi</b><small>Prikaz rokova 10. i 15. u mesecu.</small></span><input type="checkbox" checked={settings.notify_deadlines!==false} onChange={e=>setSettings({...settings,notify_deadlines:e.target.checked})}/></label><button className="btn btn-primary" onClick={saveSettings} disabled={busy}><Save size={16}/> Sačuvaj</button>{message&&<div className="demo-box">{message}</div>}</div>}
  {tab==='staff'&&isAdmin&&<div className="settings-staff-grid"><div className="card settings-card"><span className="pill"><UserPlus size={13}/> NOVI ZAPOSLENI</span><h2>Otvori nalog zaposlenom</h2><form onSubmit={createStaff}><div className="field"><label>Ime i prezime</label><input className="input" value={newStaff.full_name} onChange={e=>setNewStaff({...newStaff,full_name:e.target.value})} required/></div><div className="field-grid"><div className="field"><label>Korisničko ime</label><input className="input" value={newStaff.username} onChange={e=>setNewStaff({...newStaff,username:e.target.value.toLowerCase()})} required/></div><div className="field"><label>Email</label><input className="input" type="email" value={newStaff.email} onChange={e=>setNewStaff({...newStaff,email:e.target.value})} required/></div></div><div className="field"><label>Privremena lozinka</label><input className="input" type="password" minLength={8} value={newStaff.password} onChange={e=>setNewStaff({...newStaff,password:e.target.value})} required/></div><button className="btn btn-primary" style={{width:'100%',marginTop:14}} disabled={busy}>Kreiraj nalog zaposlenog</button></form>{staffMessage&&<div className="demo-box">{staffMessage}</div>}</div><div className="card settings-card"><span className="pill"><Users size={13}/> TIM</span><h2>Registrovani zaposleni i klijenti</h2><div className="staff-list">{(staff||[]).map((s:any)=>{const employee=s.office_role==='employee';return <div className="staff-row" key={s.user_id}><div className="staff-head"><div><b>{s.full_name||s.username}</b><span>{s.auth_email} · {employee?'Zaposleni':'Admin'}</span></div><span className="badge">{employee?(assignmentState[String(s.user_id)]||[]).length:`Svi ${clients.length}`} klijenata</span></div>{employee&&<><div className="client-assignment-list">{clients.map((c:any)=><label key={c.organization_id}><input type="checkbox" checked={(assignmentState[String(s.user_id)]||[]).includes(String(c.organization_id))} onChange={()=>toggleClient(String(s.user_id),String(c.organization_id))}/><ClientMiniLogo org={c}/><span><b>{c.name}</b><small>PIB {c.pib||'—'}</small></span></label>)}</div><button className="btn" onClick={()=>saveAssignments(String(s.user_id))} disabled={busy}>Sačuvaj dodelu klijenata</button></>}</div>})}</div>{staffMessage&&<div className="demo-box">{staffMessage}</div>}</div></div>}
  {tab==='install'&&<div className="card settings-card"><span className="pill"><Download size={13}/> DESKTOP APP</span><h2>Instaliraj FiscalBox kao aplikaciju</h2><p className="muted">Aplikacija koristi PWA/web-app režim i otvara se u posebnom prozoru, sa ikonicom na računaru. Chrome i Edge podržavaju direktan install prompt. Firefox za Windows ima Web Apps funkciju u novijim verzijama.</p><InstallAppButton/><div className="install-browser-grid"><div><b>Chrome</b><span>Install ikonica ili meni → Cast, save and share → Install page as app.</span></div><div><b>Edge</b><span>Meni … → Apps → Install this site as an app.</span></div><div><b>Firefox Windows</b><span>Web apps ikonica u adresnoj liniji → dodaj u taskbar. Firefox 143+; Microsoft Store verzija 150+.</span></div></div></div>}
  </main></div>;
}

function ClientMiniLogo({org}:any){const [bad,setBad]=React.useState(false);return <span className="client-mini-logo">{org.logo_path&&!bad?<img src={`/api/org/logo?organization_id=${org.organization_id}`} onError={()=>setBad(true)} alt=""/>:<b>{String(org.name||'K').slice(0,1)}</b>}</span>}
